hdl_global_localization:
  ros__parameters:
    ransac:
      voxel_based: true
      max_iterations: 1000000
      matching_budget: 10000
      max_correspondence_distance: 1.0
      similarity_threshold: 0.5
      correspondence_randomness: 2
      inlier_fraction: 0.25

      x_min: -10000.0
      x_max: 10000.0
      y_min: -10000.0
      y_max: 10000.0
      z_min: -10000.0
      z_max: 10000.0

      roll_min: -3.15
      roll_max: 3.15
      pitch_min: -3.15
      pitch_max: 3.15
      yaw_min: -3.15
      yaw_max: 3.15
