hdl_global_localization:
  ros__parameters:
    teaser:
      cross_check: false
      tuple_test: false
      tuple_scale: 0.95

      noise_bound: 0.5
      cbar2: 1.0
      rotation_max_iterations: 100
      rotation_gnc_factor: 1.4
      rotation_cost_threshold: 0.005
